// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouwyabccdtnqykusesxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91d3lhYmNjZHRucXlrdXNlc3hhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MzUxMzUsImV4cCI6MjA2MjAxMTEzNX0.bPY8UrWZaMM8bTm6t_7h1yVyfZQVMb7Z8rA1628iPVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);